{{- $dot := . -}}
{{- range .Values.cities }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: facebook-scraper-{{ .country | lower }}-{{ .city | lower }}
  labels:
    app.kubernetes.io/name: {{ include "facebook-scraper.name" $dot }}
    helm.sh/chart: {{ include "facebook-scraper.chart" $dot }}
    app.kubernetes.io/instance: {{ $dot.Release.Name }}
    app.kubernetes.io/managed-by: {{ $dot.Release.Service }}
spec:
  schedule: {{ .schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: scrapy
              image: "{{ $dot.Values.image.repository }}/facebook-scraper:{{ $dot.Values.image.tag }}"
              args:
                - runspider
                - -a
                - country={{ .country }}
                - -a
                - city={{ .city }}
                - -s
                - LOG_STDOUT=true
                - -s
                - LOG_LEVEL={{ $dot.Values.scrapy.logLevel }}
                - -s
                - STACKDRIVER_ENABLED={{ $dot.Values.stackdriver.enabled }}
                - -s
                - STACKDRIVER_PROJECT={{ $dot.Values.gcloud.project }}
                - facebook_scraper/spiders/events.py
                - >
                - /dev/null
              envFrom:
                - secretRef:
                    name: facebook-scraper-env
              env:
                - name: GOOGLE_APPLICATION_CREDENTIALS
                  value: "/app/google-key.json"
              volumeMounts:
                - mountPath: "/app/google-key.json"
                  name: serviceaccount
                  readOnly: true
                  subPath: google-key.json
          restartPolicy: OnFailure
          volumes:
            - name: serviceaccount
              secret:
                secretName: "facebook-scraper-sa"
{{- end }}