{{- $dot := . -}}
{{- range .Values.cities }}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: facebook-scraper-{{ .country | lower }}-{{ .city | lower }}
  labels:
    app.kubernetes.io/name: {{ include "facebook-scraper.name" $dot }}
    helm.sh/chart: {{ include "facebook-scraper.chart" $dot }}
    app.kubernetes.io/instance: {{ $dot.Release.Name }}
    app.kubernetes.io/managed-by: {{ $dot.Release.Service }}
spec:
  schedule: {{ .schedule }}
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: scrapy
              image: "{{ $dot.Values.repository }}/facebook-scraper:{{ $dot.Values.tag }}"
              command:
                - /bin/sh
                - -c
                - scrapy
                - -a country={{ .country }}
                - -a city={{ .city }}
              envFrom:
                - secretRef:
                    name: facebook-scraper-env
          restartPolicy: OnFailure
{{- end }}