nameOverride: ""
fullnameOverride: ""

gcloud:
  project:

scrapy:
  logLevel: DEBUG

stackdriver:
  enabled: false

image:
  repository: eu.gcr.io/nightguide-infra
  tag: 1.0.7

cities:
  - pageSlug: nl/utrecht
    schedule: "0 2 * * *"

